version: 0.0
os: linux
files:
  - source: /
    destination: /home/saas/temp-blog-platform

hooks:
  AfterInstall:
    - location: hook_afterinstall.sh
      runas: saas
    - location: hook_afterinstall_cleanup.sh
      timeout: 60
      runas: root